### ISSUE TITLE
Need a way to force specific encoding on standard and custom fields

### ISSUE THREAD

**Issue by AlexanderAmelkin** [ipmitool/frugen#11]
Currently all standard fields as well as text (non-binary) custom fields are encoded using automatic optimizer that chooses the encoding based on the field data range so that the encoded data occupies least space. That is not always the desired behavior as some FRU decoders may not support or properly support compressed encodings like BCD+ or 6-bit ASCII.

It is thus desirable to have an ability to specify the field encodings explicitly.

**Comment by ErwanAliasr1** [comment]
In my case, the issue was here :
		if (typelen < FRU_MAKETYPE(TEXT) && data[i] > '_') 

As I have numbers in fields, they were badly encoded.
I made a try with :
		if (typelen < FRU_MAKETYPE(TEXT) && data[i] > '/') { 

This made the proper string encoding for me. We probably could do > 'space'..

I wonder why you put this '_' limit for text encoding.

If this change is fine, I can make a PR for it.

**Comment by AlexanderAmelkin** [comment]
> I wonder why you put this '_' limit for text encoding.

@ErwanAliasr1, please see "IPMI Platform Management FRU Information Storage Definition v1.0, Revision 1.3" Table 13-1 "6-bit ASCII Definition":

![6bit_ascii](https://user-images.githubusercontent.com/4518124/91562660-3b4b6200-e946-11ea-87b8-69f5c41dd48a.png)

**Comment by ErwanAliasr1** [comment]
So if we have field why lower case, it becomes regular text, if we have upper case it remains 6bit.
Is there any interest are uppercasing every text ?

My BMC needs the encoding to be regular text and doesn't seems to support 6bit, would you accept a PR to enforce the encoding from the cmdline ? Should it be per option or global ?

What's your take on this ?

**Comment by AlexanderAmelkin** [comment]
I want it to be configurable both via json template and via command line options.
I'm working on it now, but the task is quite low priority on my side because with my company we've fixed it in OpenBMC so that it could decode 6-bit ASCII properly.

**Comment by AlexanderAmelkin** [comment]
> So if we have field with lower case, it becomes regular text, if we have upper case only it remains 6bit.
> Is there any interest are uppercasing every text ?

The text consisting solely of Table 13-1 characters will be encoded as 6-bit. If any character not from the table is encountered (e.g. a lowercase letter, a backtick, a curly brace, a pipe symbol, or a tilde, or any other "character from the first set of 256 characters of Unicode 6.2 (U+0000h through U+00FFh, inclusive)" outside the Table 13-1), then it will be encoded as regular text.

Please also note that if the text consists of only digits, spaces, dashes and dots, then it will be encoded as BCD+.

**Comment by ErwanAliasr1** [comment]
Thanks for your comments. We're also looking at using OpenBMC but until we are tied with AMI's stuff, frugen fails to encode properly for them.
If I can help on this work, I'd be happy to provide some code, testing or review.

**Comment by ErwanAliasr1** [comment]
Any updates on this ?

**Comment by AlexanderAmelkin** [comment]
Unfortunately, I didn't have any time to work on this so far.

**Comment by AlexanderAmelkin** [comment]
This is not fully resolved yet, see #13
